export type StabilityClass = 'Stable' | 'Common' | 'Volatile' | 'Chaotic' | 'Reality-Warping';

export interface MonsterSpecies {
  id: string;
  name: string;
  icon: string;
  stabilityClass: StabilityClass;
  baseProductionRate: number;  // energy/s per unit
  baseCost: number;
  instabilityDrain?: number;   // instability particles/s per unit (Volatile+ only)
  unlockCondition: number;     // totalEnergyProduced threshold to discover
  description: string;
}

export const CATALOG: MonsterSpecies[] = [
  // ── STABLE (12 species) ───────────────────────────────────────────────────
  {
    id: 'verdant_slime',
    name: 'Verdant Slime',
    icon: '🟢',
    stabilityClass: 'Stable',
    baseProductionRate: 0.5,
    baseCost: 10,
    unlockCondition: 0,
    description: 'The humble starter organism. Photosynthetic membrane produces trace bio-energy.',
  },
  {
    id: 'crystal_sprite',
    name: 'Crystal Sprite',
    icon: '💎',
    stabilityClass: 'Stable',
    baseProductionRate: 0.8,
    baseCost: 15,
    unlockCondition: 30,
    description: 'Resonant crystalline structure amplifies ambient energy fields.',
  },
  {
    id: 'moss_crawler',
    name: 'Moss Crawler',
    icon: '🐛',
    stabilityClass: 'Stable',
    baseProductionRate: 1.2,
    baseCost: 25,
    unlockCondition: 75,
    description: 'Slow but steady. Enzymatic decay converts organic matter into pure energy.',
  },
  {
    id: 'ember_pup',
    name: 'Ember Pup',
    icon: '🔥',
    stabilityClass: 'Stable',
    baseProductionRate: 1.8,
    baseCost: 40,
    unlockCondition: 150,
    description: 'Endothermic reactions keep its core smoldering indefinitely.',
  },
  {
    id: 'tide_hopper',
    name: 'Tide Hopper',
    icon: '🌊',
    stabilityClass: 'Stable',
    baseProductionRate: 2.5,
    baseCost: 70,
    unlockCondition: 300,
    description: 'Converts osmotic pressure gradients into electricity.',
  },
  {
    id: 'spore_drifter',
    name: 'Spore Drifter',
    icon: '🌸',
    stabilityClass: 'Stable',
    baseProductionRate: 3.5,
    baseCost: 120,
    unlockCondition: 600,
    description: 'Spore clouds catalyze atmospheric energy absorption.',
  },
  {
    id: 'sun_beetle',
    name: 'Sun Beetle',
    icon: '🪲',
    stabilityClass: 'Stable',
    baseProductionRate: 5,
    baseCost: 200,
    unlockCondition: 1200,
    description: 'Carapace cells are ultra-efficient photovoltaic converters.',
  },
  {
    id: 'root_golem',
    name: 'Root Golem',
    icon: '🌳',
    stabilityClass: 'Stable',
    baseProductionRate: 7,
    baseCost: 350,
    unlockCondition: 2500,
    description: 'Ancient root network taps deep geothermal veins.',
  },
  {
    id: 'frost_wisp',
    name: 'Frost Wisp',
    icon: '❄️',
    stabilityClass: 'Stable',
    baseProductionRate: 10,
    baseCost: 600,
    unlockCondition: 5000,
    description: 'Cryogenic metabolism harvests entropy differentials.',
  },
  {
    id: 'stone_crab',
    name: 'Stone Crab',
    icon: '🦀',
    stabilityClass: 'Stable',
    baseProductionRate: 14,
    baseCost: 1000,
    unlockCondition: 10000,
    description: 'Piezoelectric shell converts pressure into bio-energy.',
  },
  {
    id: 'thunder_moth',
    name: 'Thunder Moth',
    icon: '🦋',
    stabilityClass: 'Stable',
    baseProductionRate: 20,
    baseCost: 1800,
    unlockCondition: 20000,
    description: 'Wing vibrations ionize the local atmosphere, generating continuous current.',
  },
  {
    id: 'vine_strider',
    name: 'Vine Strider',
    icon: '🌿',
    stabilityClass: 'Stable',
    baseProductionRate: 28,
    baseCost: 3000,
    unlockCondition: 40000,
    description: 'Fibrous tendrils network across vast distances, collecting dispersed bio-energy.',
  },

  // ── COMMON (12 species) ───────────────────────────────────────────────────
  {
    id: 'plasma_hound',
    name: 'Plasma Hound',
    icon: '🐺',
    stabilityClass: 'Common',
    baseProductionRate: 40,
    baseCost: 5000,
    unlockCondition: 80000,
    description: 'Ionized breath dissolves matter into harvestable plasma streams.',
  },
  {
    id: 'acid_salamander',
    name: 'Acid Salamander',
    icon: '🦎',
    stabilityClass: 'Common',
    baseProductionRate: 58,
    baseCost: 8500,
    unlockCondition: 150000,
    description: 'Corrosive secretions break molecular bonds, releasing bound energy.',
  },
  {
    id: 'magma_turtle',
    name: 'Magma Turtle',
    icon: '🐢',
    stabilityClass: 'Common',
    baseProductionRate: 84,
    baseCost: 14000,
    unlockCondition: 280000,
    description: 'Living lava core sustains continuous nuclear fusion reactions.',
  },
  {
    id: 'lightning_ferret',
    name: 'Lightning Ferret',
    icon: '⚡',
    stabilityClass: 'Common',
    baseProductionRate: 120,
    baseCost: 24000,
    unlockCondition: 500000,
    description: 'Neural storm generates megawatt-class bio-electrical bursts.',
  },
  {
    id: 'vortex_serpent',
    name: 'Vortex Serpent',
    icon: '🐍',
    stabilityClass: 'Common',
    baseProductionRate: 175,
    baseCost: 40000,
    unlockCondition: 1000000,
    description: 'Coiled body compresses spacetime, extracting vacuum energy.',
  },
  {
    id: 'bio_moth',
    name: 'Bio Moth',
    icon: '🦗',
    stabilityClass: 'Common',
    baseProductionRate: 250,
    baseCost: 65000,
    unlockCondition: 2000000,
    description: 'Bioluminescent scales emit radiation across the full EM spectrum.',
  },
  {
    id: 'psi_panther',
    name: 'Psi Panther',
    icon: '🐆',
    stabilityClass: 'Common',
    baseProductionRate: 360,
    baseCost: 110000,
    unlockCondition: 4000000,
    description: 'Psychic field distortions convert mental energy into pure electricity.',
  },
  {
    id: 'shadow_elk',
    name: 'Shadow Elk',
    icon: '🦌',
    stabilityClass: 'Common',
    baseProductionRate: 520,
    baseCost: 180000,
    unlockCondition: 8000000,
    description: 'Phase-shifting antlers harvest dark matter interactions.',
  },
  {
    id: 'quantum_crab',
    name: 'Quantum Crab',
    icon: '🦞',
    stabilityClass: 'Common',
    baseProductionRate: 750,
    baseCost: 300000,
    unlockCondition: 15000000,
    description: 'Superposition claws simultaneously harvest multiple energy states.',
  },
  {
    id: 'phase_drake',
    name: 'Phase Drake',
    icon: '🐉',
    stabilityClass: 'Common',
    baseProductionRate: 1080,
    baseCost: 500000,
    unlockCondition: 30000000,
    description: 'Dimensional phasing extracts energy from parallel universe collisions.',
  },
  {
    id: 'echo_bear',
    name: 'Echo Bear',
    icon: '🐻',
    stabilityClass: 'Common',
    baseProductionRate: 1560,
    baseCost: 850000,
    unlockCondition: 60000000,
    description: 'Resonant growl creates standing waves that amplify ambient energy 1000×.',
  },
  {
    id: 'prism_whale',
    name: 'Prism Whale',
    icon: '🐋',
    stabilityClass: 'Common',
    baseProductionRate: 2250,
    baseCost: 1400000,
    unlockCondition: 120000000,
    description: 'Prismatic blubber diffracts cosmic rays into usable energy bands.',
  },

  // ── VOLATILE (12 species) ─────────────────────────────────────────────────
  {
    id: 'neuro_leech',
    name: 'Neuro Leech',
    icon: '🧠',
    stabilityClass: 'Volatile',
    baseProductionRate: 3250,
    baseCost: 2500000,
    instabilityDrain: 1,
    unlockCondition: 250000000,
    description: 'Siphons neural patterns directly, converting thought into energy.',
  },
  {
    id: 'void_squid',
    name: 'Void Squid',
    icon: '🦑',
    stabilityClass: 'Volatile',
    baseProductionRate: 4700,
    baseCost: 4200000,
    instabilityDrain: 1.5,
    unlockCondition: 500000000,
    description: 'Ink absorbs light itself; chromatophores generate continuous output.',
  },
  {
    id: 'ether_mantis',
    name: 'Ether Mantis',
    icon: '🦟',
    stabilityClass: 'Volatile',
    baseProductionRate: 6800,
    baseCost: 7000000,
    instabilityDrain: 2,
    unlockCondition: 1000000000,
    description: 'Prayer stance opens rifts to the ether; energy pours through.',
  },
  {
    id: 'cerebral_drake',
    name: 'Cerebral Drake',
    icon: '🦕',
    stabilityClass: 'Volatile',
    baseProductionRate: 9800,
    baseCost: 12000000,
    instabilityDrain: 3,
    unlockCondition: 2000000000,
    description: 'Oversized cortex runs reality simulations, harvesting the output.',
  },
  {
    id: 'chaos_beetle',
    name: 'Chaos Beetle',
    icon: '🪳',
    stabilityClass: 'Volatile',
    baseProductionRate: 14200,
    baseCost: 20000000,
    instabilityDrain: 4,
    unlockCondition: 5000000000,
    description: 'Carapace secretes entropy catalyst; local order collapses into energy.',
  },
  {
    id: 'fractal_serpent',
    name: 'Fractal Serpent',
    icon: '🌀',
    stabilityClass: 'Volatile',
    baseProductionRate: 20500,
    baseCost: 33000000,
    instabilityDrain: 6,
    unlockCondition: 10000000000,
    description: 'Infinite geometric loops create self-sustaining energy vortices.',
  },
  {
    id: 'entropy_wolf',
    name: 'Entropy Wolf',
    icon: '🐺',
    stabilityClass: 'Volatile',
    baseProductionRate: 29700,
    baseCost: 55000000,
    instabilityDrain: 9,
    unlockCondition: 20000000000,
    description: 'Howls collapse probability waves, converting quantum uncertainty to power.',
  },
  {
    id: 'null_orca',
    name: 'Null Orca',
    icon: '🐬',
    stabilityClass: 'Volatile',
    baseProductionRate: 43000,
    baseCost: 92000000,
    instabilityDrain: 13,
    unlockCondition: 50000000000,
    description: 'Echolocation punches holes in spacetime; dark energy flows in.',
  },
  {
    id: 'static_colossus',
    name: 'Static Colossus',
    icon: '🗿',
    stabilityClass: 'Volatile',
    baseProductionRate: 62000,
    baseCost: 155000000,
    instabilityDrain: 19,
    unlockCondition: 100000000000,
    description: 'Body is a living capacitor storing atmospheric charge at megaton scale.',
  },
  {
    id: 'gravity_wyrm',
    name: 'Gravity Wyrm',
    icon: '🪱',
    stabilityClass: 'Volatile',
    baseProductionRate: 90000,
    baseCost: 260000000,
    instabilityDrain: 28,
    unlockCondition: 250000000000,
    description: 'Dense core warps local gravity wells, extracting orbital decay energy.',
  },
  {
    id: 'temporal_hydra',
    name: 'Temporal Hydra',
    icon: '🐲',
    stabilityClass: 'Volatile',
    baseProductionRate: 130000,
    baseCost: 440000000,
    instabilityDrain: 40,
    unlockCondition: 500000000000,
    description: 'Each head exists in a different timeline; all timelines produce for you.',
  },
  {
    id: 'tachyon_kraken',
    name: 'Tachyon Kraken',
    icon: '🌊',
    stabilityClass: 'Volatile',
    baseProductionRate: 188000,
    baseCost: 730000000,
    instabilityDrain: 58,
    unlockCondition: 1000000000000,
    description: 'Moves faster than causality, harvesting energy before it is expended.',
  },

  // ── CHAOTIC (10 species) ──────────────────────────────────────────────────
  {
    id: 'psionic_titan',
    name: 'Psionic Titan',
    icon: '🧿',
    stabilityClass: 'Chaotic',
    baseProductionRate: 272000,
    baseCost: 1200000000,
    instabilityDrain: 84,
    unlockCondition: 2500000000000,
    description: 'Psychic field tears reality; the wounds bleed pure energy.',
  },
  {
    id: 'storm_leviathan',
    name: 'Storm Leviathan',
    icon: '🌪️',
    stabilityClass: 'Chaotic',
    baseProductionRate: 393000,
    baseCost: 2000000000,
    instabilityDrain: 120,
    unlockCondition: 5000000000000,
    description: 'Hurricane-class organism whose breath ionizes entire atmospheres.',
  },
  {
    id: 'dark_phoenix',
    name: 'Dark Phoenix',
    icon: '🦅',
    stabilityClass: 'Chaotic',
    baseProductionRate: 570000,
    baseCost: 3400000000,
    instabilityDrain: 175,
    unlockCondition: 10000000000000,
    description: 'Each rebirth triggers a micro-nova; harvest the aftermath.',
  },
  {
    id: 'void_colossus',
    name: 'Void Colossus',
    icon: '👁️',
    stabilityClass: 'Chaotic',
    baseProductionRate: 825000,
    baseCost: 5700000000,
    instabilityDrain: 250,
    unlockCondition: 25000000000000,
    description: 'Stare into the void; it stares back and generates terawatts.',
  },
  {
    id: 'abyssal_kraken',
    name: 'Abyssal Kraken',
    icon: '🫧',
    stabilityClass: 'Chaotic',
    baseProductionRate: 1200000,
    baseCost: 9500000000,
    instabilityDrain: 360,
    unlockCondition: 50000000000000,
    description: 'Tentacles span entire oceans; each sucker harvests tidal forces.',
  },
  {
    id: 'singularity_worm',
    name: 'Singularity Worm',
    icon: '🕳️',
    stabilityClass: 'Chaotic',
    baseProductionRate: 1730000,
    baseCost: 16000000000,
    instabilityDrain: 520,
    unlockCondition: 100000000000000,
    description: 'Intestinal tract contains a micro-singularity; everything consumed becomes energy.',
  },
  {
    id: 'entropy_hydra',
    name: 'Entropy Hydra',
    icon: '🐙',
    stabilityClass: 'Chaotic',
    baseProductionRate: 2500000,
    baseCost: 27000000000,
    instabilityDrain: 750,
    unlockCondition: 250000000000000,
    description: 'Cut one head; three grow back. Each head increases heat death by 1%.',
  },
  {
    id: 'null_leviathan',
    name: 'Null Leviathan',
    icon: '🌑',
    stabilityClass: 'Chaotic',
    baseProductionRate: 3600000,
    baseCost: 45000000000,
    instabilityDrain: 1085,
    unlockCondition: 500000000000000,
    description: 'Body is a walking null zone; physics breaks down and releases stored energy.',
  },
  {
    id: 'chaos_colossus',
    name: 'Chaos Colossus',
    icon: '💀',
    stabilityClass: 'Chaotic',
    baseProductionRate: 5200000,
    baseCost: 75000000000,
    instabilityDrain: 1570,
    unlockCondition: 1000000000000000,
    description: 'Living embodiment of entropy; its existence accelerates universal heat death.',
  },
  {
    id: 'reality_shard',
    name: 'Reality Shard',
    icon: '🔮',
    stabilityClass: 'Chaotic',
    baseProductionRate: 7500000,
    baseCost: 125000000000,
    instabilityDrain: 2270,
    unlockCondition: 2500000000000000,
    description: 'Broken piece of base reality. Each crack leaks energy from the substrate.',
  },

  // ── REALITY-WARPING (9 species) ───────────────────────────────────────────
  {
    id: 'dimension_weaver',
    name: 'Dimension Weaver',
    icon: '🕸️',
    stabilityClass: 'Reality-Warping',
    baseProductionRate: 10900000,
    baseCost: 210000000000,
    instabilityDrain: 3280,
    unlockCondition: 5000000000000000,
    description: 'Weaves new dimensions into existence; each one is a fresh energy source.',
  },
  {
    id: 'cosmic_annihilator',
    name: 'Cosmic Annihilator',
    icon: '💥',
    stabilityClass: 'Reality-Warping',
    baseProductionRate: 15800000,
    baseCost: 350000000000,
    instabilityDrain: 4740,
    unlockCondition: 10000000000000000,
    description: 'Annihilates matter-antimatter pairs at industrial scale.',
  },
  {
    id: 'void_architect',
    name: 'Void Architect',
    icon: '🏛️',
    stabilityClass: 'Reality-Warping',
    baseProductionRate: 22800000,
    baseCost: 580000000000,
    instabilityDrain: 6850,
    unlockCondition: 25000000000000000,
    description: 'Constructs pocket universes, harvests their entire Big Bang output.',
  },
  {
    id: 'reality_leech',
    name: 'Reality Leech',
    icon: '🩸',
    stabilityClass: 'Reality-Warping',
    baseProductionRate: 33000000,
    baseCost: 970000000000,
    instabilityDrain: 9900,
    unlockCondition: 50000000000000000,
    description: 'Parasitizes causality itself; every event feeds its endless hunger.',
  },
  {
    id: 'entropy_god',
    name: 'Entropy God',
    icon: '⚰️',
    stabilityClass: 'Reality-Warping',
    baseProductionRate: 47700000,
    baseCost: 1620000000000,
    instabilityDrain: 14300,
    unlockCondition: 100000000000000000,
    description: 'A deity of thermodynamic collapse. Worshippers provide instability; it provides heat death.',
  },
  {
    id: 'null_omnibus',
    name: 'Null Omnibus',
    icon: '⬛',
    stabilityClass: 'Reality-Warping',
    baseProductionRate: 69000000,
    baseCost: 2700000000000,
    instabilityDrain: 20700,
    unlockCondition: 250000000000000000,
    description: 'Contains all possible states of null. Collapses them for energy.',
  },
  {
    id: 'chaos_eternal',
    name: 'Chaos Eternal',
    icon: '♾️',
    stabilityClass: 'Reality-Warping',
    baseProductionRate: 99800000,
    baseCost: 4500000000000,
    instabilityDrain: 30000,
    unlockCondition: 500000000000000000,
    description: 'Predates the universe. Has been generating energy since before time began.',
  },
  {
    id: 'singularity_herald',
    name: 'Singularity Herald',
    icon: '🌌',
    stabilityClass: 'Reality-Warping',
    baseProductionRate: 144000000,
    baseCost: 7500000000000,
    instabilityDrain: 43400,
    unlockCondition: 1000000000000000000,
    description: 'Harbinger of the technological singularity. Its presence accelerates all evolution.',
  },
  {
    id: 'alpha_entity_seed',
    name: 'Alpha Entity (Seed)',
    icon: '🌟',
    stabilityClass: 'Reality-Warping',
    baseProductionRate: 208000000,
    baseCost: 12500000000000,
    instabilityDrain: 62800,
    unlockCondition: 2500000000000000000,
    description: 'The embryonic form of the Alpha Entity. Its awakening reshapes reality.',
  },
];

export const CATALOG_BY_ID: Record<string, MonsterSpecies> = Object.fromEntries(
  CATALOG.map((s) => [s.id, s])
);

export const STABILITY_CLASSES: StabilityClass[] = [
  'Stable',
  'Common',
  'Volatile',
  'Chaotic',
  'Reality-Warping',
];

export const CATALOG_BY_STABILITY: Record<StabilityClass, MonsterSpecies[]> = {
  Stable: CATALOG.filter((s) => s.stabilityClass === 'Stable'),
  Common: CATALOG.filter((s) => s.stabilityClass === 'Common'),
  Volatile: CATALOG.filter((s) => s.stabilityClass === 'Volatile'),
  Chaotic: CATALOG.filter((s) => s.stabilityClass === 'Chaotic'),
  'Reality-Warping': CATALOG.filter((s) => s.stabilityClass === 'Reality-Warping'),
};

export const CATALOG_SIZE = CATALOG.length;

export const STARTER_SPECIES_ID = 'verdant_slime';

const VOLATILE_PLUS: StabilityClass[] = ['Volatile', 'Chaotic', 'Reality-Warping'];
export function isVolatilePlus(stabilityClass: StabilityClass): boolean {
  return VOLATILE_PLUS.includes(stabilityClass);
}
