import type { MonsterSpecies } from "./types";

// Seed catalog — 55 species spanning all 5 stability classes and all rarity tiers.
// Proves the schema can represent the full range of 10,000-species Omni-Dex.
// Gene sequence: [prod, cost, stability, rarity, mutation, special]

export const SEED_CATALOG: MonsterSpecies[] = [

  // ══ STABLE (11 species) ════════════════════════════════════════════════════

  {
    id: "MS-0001", omniDexSlot: 1,
    name: "Verdant Slime",
    stabilityClass: "Stable", rarityTier: "Common",
    baseProductionRate: 1.0, instabilityParticleCost: 0.0,
    geneSequence: ["A","A","A","A","A","A"],
    specialTrait: "none",
    description: "A docile, oozing organism. The starter monster. Produces minimal resources but never destabilizes.",
  },
  {
    id: "MS-0002", omniDexSlot: 2,
    name: "Stone Toad",
    stabilityClass: "Stable", rarityTier: "Common",
    baseProductionRate: 1.5, instabilityParticleCost: 0.0,
    geneSequence: ["B","A","A","A","A","A"],
    specialTrait: "none",
    description: "A calcified amphibian. Its skin produces sediment that converts to building materials.",
  },
  {
    id: "MS-0003", omniDexSlot: 3,
    name: "Spore Moth",
    stabilityClass: "Stable", rarityTier: "Common",
    baseProductionRate: 1.0, instabilityParticleCost: 0.0,
    geneSequence: ["A","A","A","A","A","B"],
    specialTrait: "acid_spray",
    description: "Releases corrosive spores that dissolve inorganic matter into usable chemicals.",
  },
  {
    id: "MS-0004", omniDexSlot: 4,
    name: "Blister Crab",
    stabilityClass: "Stable", rarityTier: "Common",
    baseProductionRate: 2.0, instabilityParticleCost: 0.0,
    geneSequence: ["C","A","A","A","A","A"],
    specialTrait: "none",
    description: "Secretes pressurized fluid sacs. Burst carefully to harvest energy.",
  },
  {
    id: "MS-0005", omniDexSlot: 5,
    name: "Hollow Tortoise",
    stabilityClass: "Stable", rarityTier: "Uncommon",
    baseProductionRate: 2.5, instabilityParticleCost: 0.0,
    geneSequence: ["C","A","A","B","A","A"],
    specialTrait: "none",
    description: "Its shell is a self-sustaining biome. Houses minor sub-creatures that produce secondary goods.",
  },
  {
    id: "MS-0006", omniDexSlot: 6,
    name: "Lumen Worm",
    stabilityClass: "Stable", rarityTier: "Uncommon",
    baseProductionRate: 1.5, instabilityParticleCost: 0.0,
    geneSequence: ["B","A","A","B","A","B"],
    specialTrait: "acid_spray",
    description: "Bioluminescent tunneling worm. Digests rock and excretes refined ore.",
  },
  {
    id: "MS-0007", omniDexSlot: 7,
    name: "Quartz Elk",
    stabilityClass: "Stable", rarityTier: "Uncommon",
    baseProductionRate: 3.0, instabilityParticleCost: 0.0,
    geneSequence: ["D","A","A","B","A","A"],
    specialTrait: "none",
    description: "Grazes on mineral deposits. Antlers crystallize into tradeable gemstones.",
    unlockCondition: "breed MS-0002 + MS-0005",
  },
  {
    id: "MS-0008", omniDexSlot: 8,
    name: "Copper Mantis",
    stabilityClass: "Stable", rarityTier: "Rare",
    baseProductionRate: 4.0, instabilityParticleCost: 0.0,
    geneSequence: ["E","A","A","C","A","A"],
    specialTrait: "none",
    description: "Harvests electromagnetic radiation. Converts ambient fields to stored current.",
    unlockCondition: "breed MS-0004 + MS-0006",
  },
  {
    id: "MS-0009", omniDexSlot: 9,
    name: "Basalt Drake",
    stabilityClass: "Stable", rarityTier: "Rare",
    baseProductionRate: 5.0, instabilityParticleCost: 0.0,
    geneSequence: ["E","A","A","C","B","A"],
    specialTrait: "none",
    description: "Breathes magma jets that cool into dense construction slabs.",
  },
  {
    id: "MS-0010", omniDexSlot: 10,
    name: "Amber Colossus",
    stabilityClass: "Stable", rarityTier: "Legendary",
    baseProductionRate: 8.0, instabilityParticleCost: 0.0,
    geneSequence: ["G","A","A","D","B","A"],
    specialTrait: "none",
    description: "Ancient bio-construct encased in fossilized resin. Produces more per cycle than a mid-tier power plant.",
    unlockCondition: "breed MS-0007 + MS-0009",
  },
  {
    id: "MS-0011", omniDexSlot: 11,
    name: "Gaia Leviathan",
    stabilityClass: "Stable", rarityTier: "Singularity",
    baseProductionRate: 15.0, instabilityParticleCost: 0.0,
    geneSequence: ["G","A","A","E","A","A"],
    specialTrait: "none",
    description: "A continent-class organism. Its existence alone generates enough resources to sustain a small base indefinitely.",
    unlockCondition: "breed MS-0010 + MS-0010 (duplicate pair required)",
  },

  // ══ VOLATILE (11 species) ══════════════════════════════════════════════════

  {
    id: "MS-0012", omniDexSlot: 12,
    name: "Spark Hound",
    stabilityClass: "Volatile", rarityTier: "Common",
    baseProductionRate: 2.0, instabilityParticleCost: 0.5,
    geneSequence: ["B","B","A","A","B","A"],
    specialTrait: "none",
    description: "Crackles with static. Generates electrical bursts that, if harnessed, power low-tier systems.",
  },
  {
    id: "MS-0013", omniDexSlot: 13,
    name: "Fog Wyrm",
    stabilityClass: "Volatile", rarityTier: "Common",
    baseProductionRate: 1.5, instabilityParticleCost: 0.5,
    geneSequence: ["A","B","A","A","B","A"],
    specialTrait: "none",
    description: "Exudes dense mist that obscures neighboring structures. Reduces incoming raid detection.",
  },
  {
    id: "MS-0014", omniDexSlot: 14,
    name: "Cinderpede",
    stabilityClass: "Volatile", rarityTier: "Uncommon",
    baseProductionRate: 3.0, instabilityParticleCost: 0.5,
    geneSequence: ["C","B","A","B","B","B"],
    specialTrait: "acid_spray",
    description: "A centipede that ignites its trailing segments for propulsion. Acid spray accelerates mineral breakdown.",
  },
  {
    id: "MS-0015", omniDexSlot: 15,
    name: "Plasma Eel",
    stabilityClass: "Volatile", rarityTier: "Uncommon",
    baseProductionRate: 3.5, instabilityParticleCost: 1.0,
    geneSequence: ["C","C","A","B","C","A"],
    specialTrait: "none",
    description: "Aquatic creature contained in pressurized tanks. Plasma discharge charges adjacent bio-reactors.",
  },
  {
    id: "MS-0016", omniDexSlot: 16,
    name: "Thunder Boar",
    stabilityClass: "Volatile", rarityTier: "Uncommon",
    baseProductionRate: 4.0, instabilityParticleCost: 0.5,
    geneSequence: ["E","B","A","B","B","A"],
    specialTrait: "none",
    description: "Its charge creates shockwaves. Nearby production buildings get a burst bonus when it stampedes.",
  },
  {
    id: "MS-0017", omniDexSlot: 17,
    name: "Acid Bat Colony",
    stabilityClass: "Volatile", rarityTier: "Rare",
    baseProductionRate: 5.0, instabilityParticleCost: 1.5,
    geneSequence: ["E","B","A","C","C","B"],
    specialTrait: "acid_spray",
    description: "A swarm of corrosive micro-bats. High production but will eat through poorly shielded infrastructure.",
  },
  {
    id: "MS-0018", omniDexSlot: 18,
    name: "Frostfire Serpent",
    stabilityClass: "Volatile", rarityTier: "Rare",
    baseProductionRate: 6.0, instabilityParticleCost: 1.0,
    geneSequence: ["F","B","A","C","B","C"],
    specialTrait: "temporal_rift",
    description: "Alternates between freezing and burning states. Temporal rift ability slows adjacent structures by 20s/cycle.",
  },
  {
    id: "MS-0019", omniDexSlot: 19,
    name: "Vortex Rhino",
    stabilityClass: "Volatile", rarityTier: "Rare",
    baseProductionRate: 7.0, instabilityParticleCost: 1.0,
    geneSequence: ["G","B","A","C","B","A"],
    specialTrait: "none",
    description: "Creates localized air vortices that harvest atmospheric particulate for industrial use.",
  },
  {
    id: "MS-0020", omniDexSlot: 20,
    name: "Storm Kraken",
    stabilityClass: "Volatile", rarityTier: "Legendary",
    baseProductionRate: 12.0, instabilityParticleCost: 2.0,
    geneSequence: ["G","C","A","D","C","B"],
    specialTrait: "acid_spray",
    description: "A sky-dwelling cephalopod. Its ink dissolves atmospheric pollutants and converts them to resource streams.",
    unlockCondition: "breed MS-0018 + MS-0019",
  },
  {
    id: "MS-0021", omniDexSlot: 21,
    name: "Typhoon Leviathan",
    stabilityClass: "Volatile", rarityTier: "Singularity",
    baseProductionRate: 20.0, instabilityParticleCost: 3.5,
    geneSequence: ["G","C","A","E","D","C"],
    specialTrait: "temporal_rift",
    description: "Generates perpetual storm systems. Temporal rift ability can rewind failed breed attempts by 30 seconds.",
    unlockCondition: "breed MS-0020 + MS-0011",
  },
  {
    id: "MS-0022", omniDexSlot: 22,
    name: "Glitch Firefly",
    stabilityClass: "Volatile", rarityTier: "Common",
    baseProductionRate: 1.8, instabilityParticleCost: 0.5,
    geneSequence: ["B","B","A","A","D","A"],
    specialTrait: "none",
    description: "Emits coded light pulses that interface with base systems, occasionally triggering random bonuses.",
  },

  // ══ CHAOTIC (11 species) ═══════════════════════════════════════════════════

  {
    id: "MS-0023", omniDexSlot: 23,
    name: "Rift Leech",
    stabilityClass: "Chaotic", rarityTier: "Common",
    baseProductionRate: 3.0, instabilityParticleCost: 1.0,
    geneSequence: ["C","C","C","A","C","D"],
    specialTrait: "mind_shatter",
    description: "Attaches to dimensional seams and drains ambient energy. Mind shatter inflicts debuffs on enemy scouts.",
  },
  {
    id: "MS-0024", omniDexSlot: 24,
    name: "Entropy Fox",
    stabilityClass: "Chaotic", rarityTier: "Uncommon",
    baseProductionRate: 4.0, instabilityParticleCost: 1.5,
    geneSequence: ["C","C","C","B","C","A"],
    specialTrait: "none",
    description: "Accelerates local entropy fields. Nearby low-stability monsters produce 15% more at the cost of faster aging.",
  },
  {
    id: "MS-0025", omniDexSlot: 25,
    name: "Phase Mantis",
    stabilityClass: "Chaotic", rarityTier: "Uncommon",
    baseProductionRate: 5.0, instabilityParticleCost: 2.0,
    geneSequence: ["E","C","C","B","C","C"],
    specialTrait: "temporal_rift",
    description: "Phases between dimensions to harvest resources from parallel base configurations.",
  },
  {
    id: "MS-0026", omniDexSlot: 26,
    name: "Void Shark",
    stabilityClass: "Chaotic", rarityTier: "Rare",
    baseProductionRate: 7.0, instabilityParticleCost: 2.0,
    geneSequence: ["E","C","C","C","D","E"],
    specialTrait: "void_drain",
    description: "Swims through sub-dimensional channels. Void drain ability siphons resources from adjacent enemy bases.",
  },
  {
    id: "MS-0027", omniDexSlot: 27,
    name: "Chaos Hydra",
    stabilityClass: "Chaotic", rarityTier: "Rare",
    baseProductionRate: 8.0, instabilityParticleCost: 2.5,
    geneSequence: ["F","C","C","C","D","D"],
    specialTrait: "mind_shatter",
    description: "Each severed head regrows as a different gene variant. High mutation affinity makes every breed unpredictable.",
  },
  {
    id: "MS-0028", omniDexSlot: 28,
    name: "Fracture Wolf",
    stabilityClass: "Chaotic", rarityTier: "Rare",
    baseProductionRate: 9.0, instabilityParticleCost: 3.0,
    geneSequence: ["G","C","C","C","E","A"],
    specialTrait: "none",
    description: "Its howl fractures crystalline mineral deposits across the sector, multiplying harvest yields by 2x for 10 minutes.",
  },
  {
    id: "MS-0029", omniDexSlot: 29,
    name: "Mirage Titan",
    stabilityClass: "Chaotic", rarityTier: "Legendary",
    baseProductionRate: 14.0, instabilityParticleCost: 3.5,
    geneSequence: ["G","D","C","D","D","C"],
    specialTrait: "temporal_rift",
    description: "Exists in superposition — simultaneously producing in two time states. Doubles output every 48h.",
    unlockCondition: "breed MS-0025 + MS-0028",
  },
  {
    id: "MS-0030", omniDexSlot: 30,
    name: "Null Behemoth",
    stabilityClass: "Chaotic", rarityTier: "Legendary",
    baseProductionRate: 16.0, instabilityParticleCost: 4.0,
    geneSequence: ["G","D","C","D","E","E"],
    specialTrait: "void_drain",
    description: "A null-state creature. Feeds on absent resources — the emptier the base sector, the higher its output.",
    unlockCondition: "breed MS-0026 + MS-0027",
  },
  {
    id: "MS-0031", omniDexSlot: 31,
    name: "Singularity Beetle",
    stabilityClass: "Chaotic", rarityTier: "Singularity",
    baseProductionRate: 25.0, instabilityParticleCost: 5.0,
    geneSequence: ["G","E","C","E","E","F"],
    specialTrait: "reality_bleed",
    description: "Compresses local spacetime. Its reality bleed causes adjacent sectors to overlap, sharing production.",
    unlockCondition: "breed MS-0029 + MS-0030",
  },
  {
    id: "MS-0032", omniDexSlot: 32,
    name: "Haze Salamander",
    stabilityClass: "Chaotic", rarityTier: "Common",
    baseProductionRate: 2.5, instabilityParticleCost: 1.0,
    geneSequence: ["B","C","C","A","C","A"],
    specialTrait: "none",
    description: "Secretes hallucinogenic mist. Increases idle-resource multiplier but causes occasional false-positive alerts.",
  },
  {
    id: "MS-0033", omniDexSlot: 33,
    name: "Distortion Crab",
    stabilityClass: "Chaotic", rarityTier: "Uncommon",
    baseProductionRate: 4.5, instabilityParticleCost: 2.0,
    geneSequence: ["D","C","C","B","D","B"],
    specialTrait: "mind_shatter",
    description: "Its claws bend local physics. Buildings in the same sector operate at reduced energy cost.",
  },

  // ══ ABERRANT (11 species) ══════════════════════════════════════════════════

  {
    id: "MS-0034", omniDexSlot: 34,
    name: "Nerve Crawler",
    stabilityClass: "Aberrant", rarityTier: "Common",
    baseProductionRate: 4.0, instabilityParticleCost: 2.0,
    geneSequence: ["C","D","D","A","D","D"],
    specialTrait: "mind_shatter",
    description: "Integrates with base nerve-networks. Increases processing speed of adjacent command structures by 30%.",
  },
  {
    id: "MS-0035", omniDexSlot: 35,
    name: "Tendon Golem",
    stabilityClass: "Aberrant", rarityTier: "Uncommon",
    baseProductionRate: 6.0, instabilityParticleCost: 2.5,
    geneSequence: ["E","D","D","B","D","A"],
    specialTrait: "none",
    description: "Constructed from living sinew. Doubles as structural reinforcement; reduces base damage from instability events by 15%.",
  },
  {
    id: "MS-0036", omniDexSlot: 36,
    name: "Oculus Wyvern",
    stabilityClass: "Aberrant", rarityTier: "Rare",
    baseProductionRate: 9.0, instabilityParticleCost: 3.0,
    geneSequence: ["F","D","D","C","E","D"],
    specialTrait: "mind_shatter",
    description: "Its compound eyes perceive all electromagnetic spectra. Identifies hidden resource veins in unexplored sectors.",
  },
  {
    id: "MS-0037", omniDexSlot: 37,
    name: "Membrane Drake",
    stabilityClass: "Aberrant", rarityTier: "Rare",
    baseProductionRate: 10.0, instabilityParticleCost: 3.5,
    geneSequence: ["F","D","D","C","E","E"],
    specialTrait: "void_drain",
    description: "Wings are semi-permeable dimensional membranes. Continuously bleeds energy from adjacent dimensions.",
  },
  {
    id: "MS-0038", omniDexSlot: 38,
    name: "Parasite Crown",
    stabilityClass: "Aberrant", rarityTier: "Rare",
    baseProductionRate: 12.0, instabilityParticleCost: 4.0,
    geneSequence: ["G","D","D","C","F","A"],
    specialTrait: "none",
    description: "Not one organism but a queen-colony. Output scales with adjacent monster count: +8% per neighboring species.",
  },
  {
    id: "MS-0039", omniDexSlot: 39,
    name: "Spine Colossus",
    stabilityClass: "Aberrant", rarityTier: "Legendary",
    baseProductionRate: 18.0, instabilityParticleCost: 4.5,
    geneSequence: ["G","E","D","D","E","C"],
    specialTrait: "temporal_rift",
    description: "Dorsal spines are dimensional antennae. Temporal rift allows it to pre-compute upgrade costs 24h in advance.",
    unlockCondition: "breed MS-0036 + MS-0038",
  },
  {
    id: "MS-0040", omniDexSlot: 40,
    name: "Abyssal Hydra",
    stabilityClass: "Aberrant", rarityTier: "Legendary",
    baseProductionRate: 20.0, instabilityParticleCost: 5.0,
    geneSequence: ["G","E","D","D","F","F"],
    specialTrait: "reality_bleed",
    description: "Exists partially outside observable reality. Reality bleed causes production to overflow into global pool.",
    unlockCondition: "breed MS-0037 + MS-0039",
  },
  {
    id: "MS-0041", omniDexSlot: 41,
    name: "Eldritch Titan",
    stabilityClass: "Aberrant", rarityTier: "Singularity",
    baseProductionRate: 35.0, instabilityParticleCost: 6.0,
    geneSequence: ["G","F","D","E","G","G"],
    specialTrait: "echo_collapse",
    description: "An ancient beyond classification. Echo collapse ability retroactively boosts the last 6 hours of idle gains.",
    unlockCondition: "breed MS-0040 + MS-0030",
  },
  {
    id: "MS-0042", omniDexSlot: 42,
    name: "Hive Mantis",
    stabilityClass: "Aberrant", rarityTier: "Common",
    baseProductionRate: 3.5, instabilityParticleCost: 2.0,
    geneSequence: ["C","D","D","A","E","A"],
    specialTrait: "none",
    description: "Spawns drone sub-entities that autonomously harvest resources from adjacent unoccupied slots.",
  },
  {
    id: "MS-0043", omniDexSlot: 43,
    name: "Pressure Wurm",
    stabilityClass: "Aberrant", rarityTier: "Uncommon",
    baseProductionRate: 7.0, instabilityParticleCost: 2.5,
    geneSequence: ["F","D","D","B","D","D"],
    specialTrait: "mind_shatter",
    description: "Exerts gravitational anomalies. Compresses nearby matter into extremely dense resource nuggets.",
  },
  {
    id: "MS-0044", omniDexSlot: 44,
    name: "Fractal Serpent",
    stabilityClass: "Aberrant", rarityTier: "Rare",
    baseProductionRate: 11.0, instabilityParticleCost: 3.5,
    geneSequence: ["G","D","D","C","F","C"],
    specialTrait: "temporal_rift",
    description: "Each scale is a self-similar pattern of the whole organism. Splitting increases both halves' output by 40%.",
  },

  // ══ REALITY-WARPING (11 species) ═══════════════════════════════════════════

  {
    id: "MS-0045", omniDexSlot: 45,
    name: "Rift Wyrm",
    stabilityClass: "Reality-Warping", rarityTier: "Uncommon",
    baseProductionRate: 8.0, instabilityParticleCost: 3.5,
    geneSequence: ["E","E","E","B","E","E"],
    specialTrait: "void_drain",
    description: "Tears dimensional fabric to extract energy. Incorrect containment causes 20% base damage per hour.",
  },
  {
    id: "MS-0046", omniDexSlot: 46,
    name: "Paradox Golem",
    stabilityClass: "Reality-Warping", rarityTier: "Rare",
    baseProductionRate: 12.0, instabilityParticleCost: 5.0,
    geneSequence: ["F","E","E","C","F","E"],
    specialTrait: "reality_bleed",
    description: "Assembled from contradictory physical laws. Its existence generates a continuous reality bleed event.",
  },
  {
    id: "MS-0047", omniDexSlot: 47,
    name: "Oblivion Maw",
    stabilityClass: "Reality-Warping", rarityTier: "Rare",
    baseProductionRate: 15.0, instabilityParticleCost: 5.5,
    geneSequence: ["G","E","E","C","F","F"],
    specialTrait: "reality_bleed",
    description: "A mouth without body. Consumes and converts entire dimensional pockets into harvestable energy.",
    unlockCondition: "breed MS-0045 + MS-0046",
  },
  {
    id: "MS-0048", omniDexSlot: 48,
    name: "Cascade Leviathan",
    stabilityClass: "Reality-Warping", rarityTier: "Legendary",
    baseProductionRate: 25.0, instabilityParticleCost: 6.0,
    geneSequence: ["G","F","E","D","G","E"],
    specialTrait: "echo_collapse",
    description: "Triggers cascading reality events on a 72h cycle. Echo collapse compresses all pending idle gains into one instant.",
    unlockCondition: "breed MS-0041 + MS-0047",
  },
  {
    id: "MS-0049", omniDexSlot: 49,
    name: "Tentacle Goliath",
    stabilityClass: "Reality-Warping", rarityTier: "Legendary",
    baseProductionRate: 30.0, instabilityParticleCost: 7.0,
    geneSequence: ["G","F","E","D","G","G"],
    specialTrait: "echo_collapse",
    description: "The Goliath is the definitive Reality-Warping reactor. Outproduces a power plant 3:1 — but requires constant instability particle feed or it eats the base.",
    unlockCondition: "breed MS-0048 + MS-0040",
  },
  {
    id: "MS-0050", omniDexSlot: 50,
    name: "Void Incarnate",
    stabilityClass: "Reality-Warping", rarityTier: "Legendary",
    baseProductionRate: 40.0, instabilityParticleCost: 8.0,
    geneSequence: ["H","G","E","E","H","H"],
    specialTrait: "singularity_pulse",
    description: "The highest stable form before the Alpha Entity. Its singularity pulse resets the Omni-Dex catalog timer by 7 days.",
    unlockCondition: "breed MS-0049 + MS-0049",
  },
  {
    id: "MS-0051", omniDexSlot: 51,
    name: "Entropy Engine",
    stabilityClass: "Reality-Warping", rarityTier: "Singularity",
    baseProductionRate: 60.0, instabilityParticleCost: 10.0,
    geneSequence: ["H","H","E","E","H","H"],
    specialTrait: "singularity_pulse",
    description: "The entropy engine doesn't produce resources — it produces the concept of production. Output is applied globally.",
    unlockCondition: "breed MS-0050 + MS-0031",
  },
  {
    id: "MS-0052", omniDexSlot: 52,
    name: "Dimensional Parasite",
    stabilityClass: "Reality-Warping", rarityTier: "Rare",
    baseProductionRate: 14.0, instabilityParticleCost: 5.0,
    geneSequence: ["G","E","E","C","G","D"],
    specialTrait: "void_drain",
    description: "Latches onto the base's dimensional anchor. Void drain siphons 5% of all enemy global production.",
    unlockCondition: "breed MS-0045 + MS-0043",
  },
  {
    id: "MS-0053", omniDexSlot: 53,
    name: "Null Hydra",
    stabilityClass: "Reality-Warping", rarityTier: "Legendary",
    baseProductionRate: 28.0, instabilityParticleCost: 7.5,
    geneSequence: ["H","F","E","D","G","G"],
    specialTrait: "echo_collapse",
    description: "Exists in a null-state across seven dimensions simultaneously. Each severed head spawns in a different reality.",
    unlockCondition: "breed MS-0047 + MS-0052",
  },
  {
    id: "MS-0054", omniDexSlot: 54,
    name: "Abyssal Titan",
    stabilityClass: "Reality-Warping", rarityTier: "Singularity",
    baseProductionRate: 50.0, instabilityParticleCost: 9.0,
    geneSequence: ["H","G","E","E","H","G"],
    specialTrait: "singularity_pulse",
    description: "The product of 2+ years of breeding. Its singularity pulse triggers a 24h global production event for all guild members.",
    unlockCondition: "breed MS-0051 + MS-0053",
  },
  {
    id: "MS-0055", omniDexSlot: 55,
    name: "The Precursor",
    stabilityClass: "Reality-Warping", rarityTier: "Singularity",
    baseProductionRate: 75.0, instabilityParticleCost: 12.0,
    geneSequence: ["H","H","E","F","H","H"],
    specialTrait: "singularity_pulse",
    description: "Predecessor to the Alpha Entity. Its presence in a base triggers hidden Omni-Dex entries invisible until this slot is filled.",
    unlockCondition: "breed MS-0054 + MS-0050",
  },
];

export const CATALOG_BY_ID = Object.fromEntries(
  SEED_CATALOG.map((s) => [s.id, s]),
) as Record<string, MonsterSpecies>;

export const CATALOG_BY_STABILITY = SEED_CATALOG.reduce<Record<string, MonsterSpecies[]>>(
  (acc, s) => {
    (acc[s.stabilityClass] ??= []).push(s);
    return acc;
  },
  {},
);
