// Canonical Bio-Reactor monster catalog — 25 species, 5 per stability class.
// OmniDex slots 501–525 (reserved range for Bio-Reactor canonical set).
// Source: AETA-36 plan doc, Section 6.
import type { MonsterSpecies } from './monster/types';

export const BIO_REACTOR_CATALOG: MonsterSpecies[] = [

  // ── STABLE (5 species, MS-0501–MS-0505) ───────────────────────────────────

  {
    id: 'MS-0501', omniDexSlot: 501,
    name: 'Verdant Slime (Canonical)',
    stabilityClass: 'Stable', rarityTier: 'Common',
    baseProductionRate: 1.0, instabilityParticleCost: 0.0,
    geneSequence: ['A', 'A', 'A', 'A', 'A', 'A'],
    specialTrait: 'none',
    description: 'The canonical starter organism. Photosynthetic membrane produces trace bio-energy with zero instability overhead.',
  },
  {
    id: 'MS-0502', omniDexSlot: 502,
    name: 'Stone Toad (Canonical)',
    stabilityClass: 'Stable', rarityTier: 'Common',
    baseProductionRate: 1.5, instabilityParticleCost: 0.0,
    geneSequence: ['B', 'A', 'A', 'A', 'A', 'A'],
    specialTrait: 'none',
    description: 'Calcified amphibian whose piezoelectric skin converts pressure into steady bio-energy.',
  },
  {
    id: 'MS-0503', omniDexSlot: 503,
    name: 'Ember Pup (Canonical)',
    stabilityClass: 'Stable', rarityTier: 'Uncommon',
    baseProductionRate: 2.5, instabilityParticleCost: 0.0,
    geneSequence: ['C', 'A', 'A', 'B', 'A', 'A'],
    specialTrait: 'none',
    description: 'Endothermic pup whose internal combustion cycle generates continuous low-grade heat energy.',
  },
  {
    id: 'MS-0504', omniDexSlot: 504,
    name: 'Lumen Worm (Canonical)',
    stabilityClass: 'Stable', rarityTier: 'Uncommon',
    baseProductionRate: 3.0, instabilityParticleCost: 0.0,
    geneSequence: ['B', 'A', 'A', 'B', 'A', 'B'],
    specialTrait: 'acid_spray',
    description: 'Bioluminescent tunneling worm that digests mineral substrates into refined energy compounds.',
  },
  {
    id: 'MS-0505', omniDexSlot: 505,
    name: 'Copper Mantis (Canonical)',
    stabilityClass: 'Stable', rarityTier: 'Rare',
    baseProductionRate: 5.0, instabilityParticleCost: 0.0,
    geneSequence: ['E', 'A', 'A', 'C', 'A', 'A'],
    specialTrait: 'none',
    description: 'Conductive exoskeleton harvests ambient electromagnetic fields at high efficiency.',
    unlockCondition: 'totalEnergyProduced >= 5000',
  },

  // ── VOLATILE (5 species, MS-0506–MS-0510) ────────────────────────────────

  {
    id: 'MS-0506', omniDexSlot: 506,
    name: 'Neuro Leech (Canonical)',
    stabilityClass: 'Volatile', rarityTier: 'Uncommon',
    baseProductionRate: 8.0, instabilityParticleCost: 0.5,
    geneSequence: ['A', 'B', 'B', 'B', 'B', 'A'],
    specialTrait: 'none',
    description: 'Siphons ambient neural patterns, converting synaptic discharges into harvestable energy. Mildly unpredictable.',
  },
  {
    id: 'MS-0507', omniDexSlot: 507,
    name: 'Fractal Serpent (Canonical)',
    stabilityClass: 'Volatile', rarityTier: 'Uncommon',
    baseProductionRate: 12.0, instabilityParticleCost: 0.8,
    geneSequence: ['B', 'C', 'B', 'B', 'C', 'A'],
    specialTrait: 'temporal_rift',
    description: 'Self-similar coil patterns create micro-vortices that amplify energy yield. Occasional spatial distortions.',
  },
  {
    id: 'MS-0508', omniDexSlot: 508,
    name: 'Entropy Wolf (Canonical)',
    stabilityClass: 'Volatile', rarityTier: 'Rare',
    baseProductionRate: 18.0, instabilityParticleCost: 1.2,
    geneSequence: ['C', 'C', 'B', 'C', 'C', 'B'],
    specialTrait: 'void_drain',
    description: 'Howls collapse local probability waves into usable power. Containment advisable but not mandatory.',
    unlockCondition: 'purchasedContainment includes containment_volatile',
  },
  {
    id: 'MS-0509', omniDexSlot: 509,
    name: 'Void Squid (Canonical)',
    stabilityClass: 'Volatile', rarityTier: 'Rare',
    baseProductionRate: 25.0, instabilityParticleCost: 1.8,
    geneSequence: ['D', 'C', 'B', 'C', 'D', 'C'],
    specialTrait: 'reality_bleed',
    description: 'Chromatic ink absorbs light itself; chromatophores generate continuous high-output current.',
    unlockCondition: 'purchasedContainment includes containment_volatile',
  },
  {
    id: 'MS-0510', omniDexSlot: 510,
    name: 'Tachyon Kraken (Canonical)',
    stabilityClass: 'Volatile', rarityTier: 'Legendary',
    baseProductionRate: 40.0, instabilityParticleCost: 3.0,
    geneSequence: ['E', 'D', 'B', 'D', 'E', 'D'],
    specialTrait: 'echo_collapse',
    description: 'Moves faster than causality, harvesting energy before it is expended. Unpredictable but manageable.',
    unlockCondition: 'purchasedContainment includes containment_volatile',
  },

  // ── CHAOTIC (5 species, MS-0511–MS-0515) ─────────────────────────────────

  {
    id: 'MS-0511', omniDexSlot: 511,
    name: 'Psionic Titan (Canonical)',
    stabilityClass: 'Chaotic', rarityTier: 'Rare',
    baseProductionRate: 70.0, instabilityParticleCost: 5.0,
    geneSequence: ['A', 'D', 'C', 'C', 'D', 'A'],
    specialTrait: 'mind_shatter',
    description: 'Psychic field tears local reality; the wounds bleed pure energy at prodigious rates.',
  },
  {
    id: 'MS-0512', omniDexSlot: 512,
    name: 'Storm Leviathan (Canonical)',
    stabilityClass: 'Chaotic', rarityTier: 'Rare',
    baseProductionRate: 110.0, instabilityParticleCost: 8.0,
    geneSequence: ['B', 'E', 'C', 'C', 'E', 'B'],
    specialTrait: 'void_drain',
    description: 'Hurricane-class organism whose breath ionizes entire micro-atmospheres within the containment zone.',
  },
  {
    id: 'MS-0513', omniDexSlot: 513,
    name: 'Dark Phoenix (Canonical)',
    stabilityClass: 'Chaotic', rarityTier: 'Legendary',
    baseProductionRate: 175.0, instabilityParticleCost: 12.0,
    geneSequence: ['C', 'E', 'C', 'D', 'F', 'C'],
    specialTrait: 'reality_bleed',
    description: 'Each rebirth triggers a micro-nova within containment; harvest the energy aftermath.',
    unlockCondition: 'purchasedContainment includes containment_chaotic',
  },
  {
    id: 'MS-0514', omniDexSlot: 514,
    name: 'Void Colossus (Canonical)',
    stabilityClass: 'Chaotic', rarityTier: 'Legendary',
    baseProductionRate: 280.0, instabilityParticleCost: 20.0,
    geneSequence: ['D', 'F', 'C', 'D', 'G', 'D'],
    specialTrait: 'echo_collapse',
    description: 'An entity of absolute null. Its gaze converts matter into raw energy on contact.',
    unlockCondition: 'purchasedContainment includes containment_chaotic',
  },
  {
    id: 'MS-0515', omniDexSlot: 515,
    name: 'Abyssal Kraken (Canonical)',
    stabilityClass: 'Chaotic', rarityTier: 'Singularity',
    baseProductionRate: 450.0, instabilityParticleCost: 32.0,
    geneSequence: ['E', 'G', 'C', 'E', 'H', 'E'],
    specialTrait: 'singularity_pulse',
    description: 'Tentacles span the entire containment chamber; each sucker harvests tidal dimensional forces.',
    unlockCondition: 'purchasedContainment includes containment_chaotic',
  },

  // ── ABERRANT (5 species, MS-0516–MS-0520) ────────────────────────────────

  {
    id: 'MS-0516', omniDexSlot: 516,
    name: 'Null Leviathan (Canonical)',
    stabilityClass: 'Aberrant', rarityTier: 'Rare',
    baseProductionRate: 800.0, instabilityParticleCost: 60.0,
    geneSequence: ['A', 'E', 'D', 'C', 'E', 'A'],
    specialTrait: 'void_drain',
    description: 'Body is a walking null zone; local physics break down and release enormous stored energy.',
  },
  {
    id: 'MS-0517', omniDexSlot: 517,
    name: 'Chaos Colossus (Canonical)',
    stabilityClass: 'Aberrant', rarityTier: 'Legendary',
    baseProductionRate: 1350.0, instabilityParticleCost: 100.0,
    geneSequence: ['B', 'F', 'D', 'D', 'F', 'C'],
    specialTrait: 'echo_collapse',
    description: 'Living embodiment of entropy. Its existence accelerates thermodynamic collapse — and harvests every joule.',
    unlockCondition: 'purchasedContainment includes containment_aberrant',
  },
  {
    id: 'MS-0518', omniDexSlot: 518,
    name: 'Reality Shard (Canonical)',
    stabilityClass: 'Aberrant', rarityTier: 'Legendary',
    baseProductionRate: 2200.0, instabilityParticleCost: 165.0,
    geneSequence: ['C', 'G', 'D', 'D', 'G', 'D'],
    specialTrait: 'reality_bleed',
    description: 'Broken piece of base reality. Each fracture line leaks energy from the substrate of existence.',
    unlockCondition: 'purchasedContainment includes containment_aberrant',
  },
  {
    id: 'MS-0519', omniDexSlot: 519,
    name: 'Temporal Hydra (Canonical)',
    stabilityClass: 'Aberrant', rarityTier: 'Legendary',
    baseProductionRate: 3600.0, instabilityParticleCost: 270.0,
    geneSequence: ['D', 'G', 'D', 'E', 'G', 'E'],
    specialTrait: 'temporal_rift',
    description: 'Each head exists in a different timeline; all timelines produce for you simultaneously.',
    unlockCondition: 'purchasedContainment includes containment_aberrant',
  },
  {
    id: 'MS-0520', omniDexSlot: 520,
    name: 'Entropy Hydra (Canonical)',
    stabilityClass: 'Aberrant', rarityTier: 'Singularity',
    baseProductionRate: 5800.0, instabilityParticleCost: 440.0,
    geneSequence: ['E', 'H', 'D', 'E', 'H', 'F'],
    specialTrait: 'singularity_pulse',
    description: 'Cut one head; three grow back — each one a new energy source. Heat death accelerated for your benefit.',
    unlockCondition: 'purchasedContainment includes containment_aberrant',
  },

  // ── REALITY-WARPING (5 species, MS-0521–MS-0525) ─────────────────────────

  {
    id: 'MS-0521', omniDexSlot: 521,
    name: 'Dimension Weaver (Canonical)',
    stabilityClass: 'Reality-Warping', rarityTier: 'Legendary',
    baseProductionRate: 10000.0, instabilityParticleCost: 800.0,
    geneSequence: ['A', 'F', 'E', 'D', 'F', 'A'],
    specialTrait: 'temporal_rift',
    description: 'Weaves new pocket dimensions into existence; each one is a fresh energy source for harvest.',
    unlockCondition: 'purchasedContainment includes containment_reality_warping',
  },
  {
    id: 'MS-0522', omniDexSlot: 522,
    name: 'Void Architect (Canonical)',
    stabilityClass: 'Reality-Warping', rarityTier: 'Legendary',
    baseProductionRate: 17000.0, instabilityParticleCost: 1350.0,
    geneSequence: ['B', 'G', 'E', 'E', 'G', 'C'],
    specialTrait: 'void_drain',
    description: 'Constructs miniature universes within the containment field, harvesting their entire Big Bang output.',
    unlockCondition: 'purchasedContainment includes containment_reality_warping',
  },
  {
    id: 'MS-0523', omniDexSlot: 523,
    name: 'Reality Leech (Canonical)',
    stabilityClass: 'Reality-Warping', rarityTier: 'Singularity',
    baseProductionRate: 28000.0, instabilityParticleCost: 2200.0,
    geneSequence: ['C', 'G', 'E', 'E', 'H', 'D'],
    specialTrait: 'reality_bleed',
    description: 'Parasitizes causality itself. Every event in the observable universe feeds its endless hunger.',
    unlockCondition: 'purchasedContainment includes containment_reality_warping',
  },
  {
    id: 'MS-0524', omniDexSlot: 524,
    name: 'Entropy God (Canonical)',
    stabilityClass: 'Reality-Warping', rarityTier: 'Singularity',
    baseProductionRate: 46000.0, instabilityParticleCost: 3600.0,
    geneSequence: ['D', 'H', 'E', 'F', 'H', 'E'],
    specialTrait: 'echo_collapse',
    description: 'A deity of thermodynamic collapse. Worshippers provide instability; it delivers the heat death dividend.',
    unlockCondition: 'purchasedContainment includes containment_reality_warping',
  },
  {
    id: 'MS-0525', omniDexSlot: 525,
    name: 'Singularity Herald (Canonical)',
    stabilityClass: 'Reality-Warping', rarityTier: 'Singularity',
    baseProductionRate: 75000.0, instabilityParticleCost: 6000.0,
    geneSequence: ['E', 'H', 'E', 'G', 'H', 'H'],
    specialTrait: 'singularity_pulse',
    description: 'Harbinger of the technological singularity. Its presence accelerates all local evolution — and energy output.',
    unlockCondition: 'purchasedContainment includes containment_reality_warping',
  },
];

export const BIO_REACTOR_CATALOG_BY_ID: Record<string, MonsterSpecies> = Object.fromEntries(
  BIO_REACTOR_CATALOG.map((s) => [s.id, s]),
);

export const BIO_REACTOR_CATALOG_SIZE = BIO_REACTOR_CATALOG.length;
