import type { Upgrade } from './types';

export const UPGRADE_DEFINITIONS: Upgrade[] = [
  {
    id: 'efficiency_1',
    name: 'Cellular Efficiency I',
    description: '+50% energy output from all monsters',
    cost: 50,
    multiplier: 1.5,
    purchased: false,
  },
  {
    id: 'efficiency_2',
    name: 'Cellular Efficiency II',
    description: 'Double energy output from all monsters',
    cost: 500,
    multiplier: 2.0,
    purchased: false,
    unlockAt: 200,
  },
  {
    id: 'metabolic_surge',
    name: 'Metabolic Surge',
    description: 'Bio-electric output tripled',
    cost: 5_000,
    multiplier: 3.0,
    purchased: false,
    unlockAt: 2_000,
  },
  {
    id: 'quantum_absorption',
    name: 'Quantum Absorption',
    description: 'Energy absorption becomes non-linear (+5×)',
    cost: 50_000,
    multiplier: 5.0,
    purchased: false,
    unlockAt: 20_000,
  },
  {
    id: 'void_resonance',
    name: 'Void Resonance',
    description: 'Tap into dimensional energy streams (+10×)',
    cost: 500_000,
    multiplier: 10.0,
    purchased: false,
    unlockAt: 200_000,
  },
  {
    id: 'singularity_pulse',
    name: 'Singularity Pulse',
    description: 'Reality fractures grant exponential yield (+25×)',
    cost: 5_000_000,
    multiplier: 25.0,
    purchased: false,
    unlockAt: 2_000_000,
  },
];
